### ISSUE TITLE
docopt 0.7.0.5 fails to build with GHC 8.10.7 and 9.0.1

### ISSUE THREAD

**Issue by andreasabel** [docopt/docopt.hs#47]
docopt 0.7.0.5 needs to be revised on hackage to `base < 4.14` since it does not build with GHC 8.10 or 9.0.  (I suspect versions 0.7.0.<5 have the same problem.)

Revisions can be made at e.g. https://hackage.haskell.org/package/docopt/maintain

Error (GHC 9.0.1):
```
[ 6 of 10] Compiling System.Console.Docopt.Public ( System/Console/Docopt/Public.hs, dist/build/System/Console/Docopt/Public.o, dist/build/System/Console/Docopt/Public.dyn_o )

System/Console/Docopt/Public.hs:195:17: error:
    • Could not deduce (MonadFail m) arising from a use of ‘fail’
      from the context: Monad m
        bound by the type signature for:
                   getFirstArg :: forall (m :: * -> *).
                                  Monad m =>
                                  Arguments -> Option -> m String
        at System/Console/Docopt/Public.hs:193:1-57
      Possible fix:
        add (MonadFail m) to the context of
          the inferred type of failure :: m a
          or the type signature for:
               getFirstArg :: forall (m :: * -> *).
                              Monad m =>
                              Arguments -> Option -> m String
```

See also https://matrix.hackage.haskell.org/#/package/docopt for where the bounds to not reflect buildability (look for the red FAIL entries).

**Comment by andreasabel** [comment]
Thanks for your work in #44 on advancing `docopt`, @FullstackGJJ.
However, this issue isn't fixed; with GHC 8.10, `cabal` still selects version `0.7.0.5` of docopt and then fails to compile (see below).

This issue is fixed by making a hackage revision on the already released version 0.7.0.5, see my original comment.

Build log:
```
$ cabal install docopt
Resolving dependencies...
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - docopt-0.7.0.5 (lib) (requires build)
Configuring library for docopt-0.7.0.5..
Preprocessing library for docopt-0.7.0.5..
Building library for docopt-0.7.0.5..
[ 1 of 10] Compiling System.Console.Docopt.ApplicativeParsec ( System/Console/Docopt/ApplicativeParsec.hs, dist/build/System/Console/Docopt/ApplicativeParsec.o, dist/build/System/Console/Docopt/ApplicativeParsec.dyn_o )
[ 2 of 10] Compiling System.Console.Docopt.ParseUtils ( System/Console/Docopt/ParseUtils.hs, dist/build/System/Console/Docopt/ParseUtils.o, dist/build/System/Console/Docopt/ParseUtils.dyn_o )
[ 3 of 10] Compiling System.Console.Docopt.Types ( System/Console/Docopt/Types.hs, dist/build/System/Console/Docopt/Types.o, dist/build/System/Console/Docopt/Types.dyn_o )
[ 4 of 10] Compiling System.Console.Docopt.QQ.Instances ( System/Console/Docopt/QQ/Instances.hs, dist/build/System/Console/Docopt/QQ/Instances.o, dist/build/System/Console/Docopt/QQ/Instances.dyn_o )

System/Console/Docopt/QQ/Instances.hs:11:10: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘liftTyped’
    • In the instance declaration for ‘Lift (M.Map k v)’
   |
11 | instance (Lift k, Lift v) => Lift (M.Map k v) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ 5 of 10] Compiling System.Console.Docopt.OptParse ( System/Console/Docopt/OptParse.hs, dist/build/System/Console/Docopt/OptParse.o, dist/build/System/Console/Docopt/OptParse.dyn_o )
[ 6 of 10] Compiling System.Console.Docopt.Public ( System/Console/Docopt/Public.hs, dist/build/System/Console/Docopt/Public.o, dist/build/System/Console/Docopt/Public.dyn_o )

System/Console/Docopt/Public.hs:195:17: error:
    • Could not deduce (MonadFail m) arising from a use of ‘fail’
      from the context: Monad m
        bound by the type signature for:
                   getFirstArg :: forall (m :: * -> *).
                                  Monad m =>
                                  Arguments -> Option -> m String
        at System/Console/Docopt/Public.hs:193:1-57
      Possible fix:
        add (MonadFail m) to the context of
          the inferred type of failure :: m a
          or the type signature for:
               getFirstArg :: forall (m :: * -> *).
                              Monad m =>
                              Arguments -> Option -> m String
    • In the expression: fail $ "no argument given: " ++ show opt
      In an equation for ‘failure’:
          failure = fail $ "no argument given: " ++ show opt
      In the expression:
        let failure = fail $ "no argument given: " ++ show opt
        in
          case opt `M.lookup` args of
            Nothing -> failure
            Just val
              -> case val of
                   MultiValue vs -> ...
                   Value v -> return v
                   _ -> failure
    |
195 |   let failure = fail $ "no argument given: " ++ show opt
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: cabal: Failed to build docopt-0.7.0.5.
```

**Comment by FullstackGJJ** [comment]
I learned the hard way that version 0.7.0.5 and 0.7.0.<5 will not work for GHC 8.10. Fixing base issue will reveal template-haskell versioning issues (I was informed that template-haskell versions are tied to specific GHC) I'm currently working on a fix for it (might become a version 0.8.0.0)

**Comment by andreasabel** [comment]
To repeat myself:

> docopt 0.7.0.5 needs to be revised on hackage to `base < 4.14` since it does not build with GHC 8.10 or 9.0. (I suspect versions 0.7.0.<5 have the same problem.)
> 
> Revisions can be made at e.g. [hackage.haskell.org/package/docopt/maintain](https://hackage.haskell.org/package/docopt/maintain)

This issue talks only about the `base` constraint of `docopt-0.7.0.5`.

@FullstackGJJ wrote:
> I learned the hard way that version 0.7.0.5 and 0.7.0.<5 will not work for GHC 8.10.

Maybe you want to set up continuous integration to test PRs with several GHC versions:
https://github.com/haskell-CI/haskell-ci

**Comment by FullstackGJJ** [comment]
@andreasabel Made the necessary revision for 0.7.0.5, will be doing the same for the remaining 0.7.0.<5 later. I plan to set up continuous integration later as well.

**Comment by andreasabel** [comment]
Excellent, @FullstackGJJ !
